import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/Produk/lazychair.jpg',
    title: 'Cozy Chair',
    rating: 5,
    ratingCount: 8,
    category: 'Beginner',
  },
  {
    id: 2,
    cover: '/images/Produk/coffietab.png',
    title: 'Coffee Table',
    rating: 5,
    ratingCount: 15,
    category: 'Intermediate',
  },
  {
    id: 3,
    cover: '/images/Produk/wardrobe.jpg',
    title: 'Wardrobe',
    rating: 4,
    ratingCount: 12,
    category: 'Intermediate',
  },
  {
    id: 4,
    cover: '/images/revisi/DSC00013.png',
    title: 'Bag',
    rating: 4,
    ratingCount: 32,
    category: 'Intermediate',
  },
  {
    id: 5,
    cover: '/images/Produk/modern_book_rak.jpg',
    title: 'Modern Book Shelves',
    rating: 5,
    ratingCount: 14,
    category: 'Beginner',
  },
  {
    id: 6,
    cover: '/images/Produk/DressTable.png',
    title: 'Dressing table',
    rating: 4.5,
    ratingCount: 6,
    category: 'Beginner',
  },
  {
    id: 7,
    cover: '/images/revisi/DSC00064.png',
    title: 'Flat Shoes',
    rating: 4,
    ratingCount: 10,
    category: 'Beginner',
  },
  {
    id: 8,
    cover: '/images/revisi/DSC00027.png',
    title: 'Bag',
    rating: 3.8,
    ratingCount: 9,
    category: 'Beginner',
  },
  {
    id: 9,
    cover: '/images/revisi/DSC00100.png',
    title: 'Batik',
    rating: 4.3,
    ratingCount: 11,
    category: 'Beginner',
  },
]
