import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/Produk/lazychair.jpg',
    title: 'Cozy Chair',
    rating: 5,
    ratingCount: 8,
    price: 25,
    category: 'Beginner',
  },
  {
    id: 2,
    cover: '/images/Produk/coffietab.png',
    title: 'Coffee Table',
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: 'Intermediate',
  },
  {
    id: 3,
    cover: '/images/Produk/DSC00071.jpg',
    title: 'Shoes',
    rating: 4,
    ratingCount: 7,
    price: 30,
    category: 'Beginner',
  },
  {
    id: 4,
    cover: '/images/Produk/wardrobe.jpg',
    title: 'Wardrobe',
    rating: 4,
    ratingCount: 12,
    price: 30,
    category: 'Intermediate',
  },
  {
    id: 5,
    cover: '/images/Produk/modern_book_rak.jpg',
    title: 'Modern Book Shelves',
    rating: 4,
    ratingCount: 32,
    price: 35,
    category: 'Intermediate',
  },
  {
    id: 6,
    cover: '/images/Produk/DSC00019.jpg',
    title: 'Bag',
    rating: 5,
    ratingCount: 14,
    price: 35,
    category: 'Beginner',
  },
  {
    id: 7,
    cover: '/images/Produk/DressTable.png',
    title: 'Dressing table',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Beginner',
  },
]
